# Generated by Django 3.1.7 on 2021-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
