# Generated by Django 3.1.7 on 2021-03-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210331_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupsModel',
            new_name='Group',
        ),
    ]
