# Generated by Django 3.1.7 on 2021-03-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210331_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
