# Generated by Django 3.1.7 on 2021-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_description_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
