# Generated by Django 3.1.7 on 2021-06-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20210516_1138'),
        ('groups', '0014_auto_20210516_1247'),
    ]

    operations = [
    ]
