# Generated by Django 3.1.7 on 2021-06-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
